### ISSUE TITLE
Cannot run: NameError: name 'Image' is not defined

### ISSUE THREAD

**Issue by rithvikvibhu** [JithLord/BlackOutPoetry#4]
Running `python main.py` says:

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from code2 import encodeImage,decodeImage
  File "/tmp/BlackOutPoetry/code2.py", line 1, in <module>
    im1 = Image.open('some.jpg')    #The image before encoding
NameError: name 'Image' is not defined
```

**Comment by JithLord** [comment]
Required commenting the part of the program. Issue is now resolved.

Thank you
